In [1]:
## Task A ##

import numpy as np

def standardize(D):
    zero_mean_D = D - np.mean(D,axis = 0)
    unit_variance_D = zero_mean_D / np.std(zero_mean_D,axis = 0)
    print(np.std(unit_variance_D,axis=0))
    print(np.mean(unit_variance_D,axis=0))
    return unit_variance_D


D = np.random.randn(4,6)
print(D)
D_standard = standardize(D)
print(D_standard)

[[-0.37509591 -0.17092991 -0.87002985 -1.07916395  1.26731238  0.83672779]
 [-1.44827273  1.16967796  0.80856312  0.76950602  0.10722155 -1.27670453]
 [-0.9196466   0.92221748  0.99766907  0.99308524  0.97780943  2.93631188]
 [ 0.23204748  0.34022126  0.69316615 -0.15232127  1.29713402  1.00053865]]
[1. 1. 1. 1. 1. 1.]
[ 1.11022302e-16 -2.77555756e-17  0.00000000e+00 -2.77555756e-17
  5.55111512e-17 -4.85722573e-17]
[[ 0.40435698 -1.41336735 -1.71353666 -1.47632052  0.73747728 -0.02513936]
 [-1.31324982  1.1602579   0.5382198   0.77562955 -1.67288312 -1.44230122]
 [-0.46718996  0.68519689  0.79189687  1.04798171  0.1359671   1.38273658]
 [ 1.3760828  -0.43208745  0.38341999 -0.34729074  0.79943873  0.084704  ]]


In [10]:
## Task B ##

M1 = np.random.randn(2,1)
M2 = np.random.randn(2,4)

def pairwise_dist(M1,M2):
    N1 = np.size(M1,1)
    N2 = np.size(M2,1)
    distance_matrix = np.zeros([N1,N2])
    for i in range(N1):
        for j in range(N2):
            distance_matrix[i,j] = np.linalg.norm(M1[:,i]-M2[:,j])
    return distance_matrix

print(pairwise_dist(M1,M2))

[[ 2.12347592]
 [-1.17769038]]
[[-0.5468814   1.35866151  1.20516557  1.21243673]
 [-1.37520912  0.3261373   0.67151054 -0.13554774]]
[[2.6776523  1.68713922 2.06466412 1.38421591]]


In [ ]:
## Task C ##

